---
title: "Tema2"
author: "Angel Berlanas Vicente"
subject: "Ejemplo de Salida"
date: "15/2/2022"
output:
  html_document:
    toc: true
    toc_depth: 2
    fig_caption: true
---

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Markdown
## Introducción

Vamos a leer los datos de diferentes paises.

Estos datos provienen de la libreria de `gapminder`.

```{r datos-library}
library(gapminder)
datos_brutos <- gapminder::gapminder
summary(datos_brutos)
```
\newpage
## Incluyendo Gráficos

Con esos datos podemos generar un Histograma
```{r datos-histograma}

library(gapminder)
datos_brutos <- gapminder::gapminder
hist(datos_brutos$lifeExp)

```


O un diagrama de Tarta
```{r datos-pastel}

library(gapminder)
datos_brutos <- gapminder::gapminder
pie(table(datos_brutos$continent))

```


También tenemos el famosérrimo diagrama de Caja-Bigote
```{r datos-caja-bigote}

library(gapminder)
datos_brutos <- gapminder::gapminder
boxplot(datos_brutos$lifeExp, horizontal = TRUE)
#Now we add the mean
abline(v=mean(datos_brutos$lifeExp), col = "blue")

```


